# TRAINS

TRAINS = [
    {
        "id": 1, "name": "5UP - Green Line Express", "time": "22:00",
        "source": "Karachi Cantonment", "destination": "Margala",
        "stops": ["Karachi Cantonment", "Hyderabad", "Rohri", "Bahawalpur",
                  "Khanewal", "Lahore", "Rawalpindi", "Margala"],
        "price_factor": 1.2,
    },
    {
        "id": 2, "name": "41UP - Karakoram Express", "time": "15:30",
        "source": "Karachi Cantonment", "destination": "Lahore",
        "stops": ["Karachi Cantonment", "Hyderabad", "Nawabshah",
                  "Sukkur", "Bahawalpur", "Khanewal", "Sahiwal", "Lahore"],
        "price_factor": 1.0,
    },
    {
        "id": 3, "name": "33UP - Pak Business Express", "time": "16:00",
        "source": "Karachi Cantonment", "destination": "Lahore",
        "stops": ["Karachi Cantonment", "Hyderabad",
                  "Sukkur", "Multan Cantonment", "Faisalabad", "Lahore"],
        "price_factor": 1.1,
    },
    {
        "id": 4, "name": "17UP - Millat Express", "time": "14:15",
        "source": "Karachi Cantonment", "destination": "Sargodha",
        "stops": ["Karachi Cantonment", "Hyderabad", "Nawabshah",
                  "Sukkur", "Multan Cantonment", "Khanewal", "Faisalabad", "Sargodha"],
        "price_factor": 0.9,
    },
    {
        "id": 5, "name": "9UP - Allama Iqbal Express", "time": "14:00",
        "source": "Karachi Cantonment", "destination": "Sialkot",
        "stops": ["Karachi Cantonment", "Hyderabad",
                  "Sukkur", "Bahawalpur", "Lahore", "Gujranwala", "Sialkot"],
        "price_factor": 0.85,
    },
    {
        "id": 6, "name": "1UP - Khyber Mail", "time": "22:15",
        "source": "Karachi Cantonment", "destination": "Peshawar City",
        "stops": ["Karachi Cantonment", "Hyderabad", "Nawabshah",
                  "Sukkur", "Multan Cantonment", "Lahore", "Rawalpindi", "Margala",
                  "Peshawar Cantonment", "Peshawar City"],
        "price_factor": 0.95,
    },
    {
        "id": 7, "name": "6DN - Green Line Express", "time": "20:00",
        "source": "Margala", "destination": "Karachi Cantonment",
        "stops": ["Margala", "Rawalpindi", "Lahore", "Khanewal",
                  "Bahawalpur", "Rohri", "Hyderabad", "Karachi Cantonment"],
        "price_factor": 1.2,
    },
    {
        "id": 8, "name": "42DN - Karakoram Express", "time": "15:00",
        "source": "Lahore", "destination": "Karachi Cantonment",
        "stops": ["Lahore", "Sahiwal", "Khanewal", "Bahawalpur",
                  "Sukkur", "Nawabshah", "Hyderabad", "Karachi Cantonment"],
        "price_factor": 1.0,
    },
    {
        "id": 9, "name": "34DN - Pak Business Express", "time": "16:30",
        "source": "Lahore", "destination": "Karachi Cantonment",
        "stops": ["Lahore", "Faisalabad", "Multan Cantonment",
                  "Sukkur", "Hyderabad", "Karachi Cantonment"],
        "price_factor": 1.1,
    },
    {
        "id": 10, "name": "18DN - Millat Express", "time": "13:30",
        "source": "Sargodha", "destination": "Karachi Cantonment",
        "stops": ["Sargodha", "Faisalabad", "Khanewal", "Multan Cantonment",
                  "Sukkur", "Nawabshah", "Hyderabad", "Karachi Cantonment"],
        "price_factor": 0.9,
    },
    {
        "id": 11, "name": "10DN - Allama Iqbal Express", "time": "12:00",
        "source": "Sialkot", "destination": "Karachi Cantonment",
        "stops": ["Sialkot", "Gujranwala", "Lahore", "Bahawalpur",
                  "Sukkur", "Hyderabad", "Karachi Cantonment"],
        "price_factor": 0.85,
    },
    {
        "id": 12, "name": "2DN - Khyber Mail", "time": "06:00",
        "source": "Peshawar City", "destination": "Karachi Cantonment",
        "stops": ["Peshawar City", "Peshawar Cantonment", "Margala", "Rawalpindi",
                  "Lahore", "Multan Cantonment", "Sukkur", "Nawabshah",
                  "Hyderabad", "Karachi Cantonment"],
        "price_factor": 0.95,
    },
    {
        "id": 13, "name": "21UP - Lahore Express", "time": "08:00",
        "source": "Rawalpindi", "destination": "Lahore",
        "stops": ["Rawalpindi", "Margala", "Gujranwala", "Lahore"],
        "price_factor": 0.9,
    },
    {
        "id": 14, "name": "22DN - Lahore Express", "time": "18:00",
        "source": "Lahore", "destination": "Rawalpindi",
        "stops": ["Lahore", "Gujranwala", "Margala", "Rawalpindi"],
        "price_factor": 0.9,
    },
    {
        "id": 15, "name": "7UP - Awam Express", "time": "10:00",
        "source": "Karachi Cantonment", "destination": "Quetta",
        "stops": ["Karachi Cantonment", "Hyderabad",
                  "Nawabshah", "Sukkur", "Quetta"],
        "price_factor": 0.8,
    },
    {
        "id": 16, "name": "8DN - Awam Express", "time": "09:00",
        "source": "Quetta", "destination": "Karachi Cantonment",
        "stops": ["Quetta", "Sukkur", "Nawabshah",
                  "Hyderabad", "Karachi Cantonment"],
        "price_factor": 0.8,
    },
    {
        "id": 17, "name": "11UP - Peshawar Express", "time": "07:30",
        "source": "Rawalpindi", "destination": "Peshawar City",
        "stops": ["Rawalpindi", "Margala", "Peshawar Cantonment", "Peshawar City"],
        "price_factor": 0.85,
    },
    {
        "id": 18, "name": "12DN - Peshawar Express", "time": "17:00",
        "source": "Peshawar City", "destination": "Rawalpindi",
        "stops": ["Peshawar City", "Peshawar Cantonment", "Margala", "Rawalpindi"],
        "price_factor": 0.85,
    },
    {
        "id": 19, "name": "23UP - Chenab Express", "time": "09:00",
        "source": "Faisalabad", "destination": "Lahore",
        "stops": ["Faisalabad", "Sahiwal", "Lahore"],
        "price_factor": 0.8,
    },
    {
        "id": 20, "name": "24DN - Chenab Express", "time": "19:00",
        "source": "Lahore", "destination": "Faisalabad",
        "stops": ["Lahore", "Sahiwal", "Faisalabad"],
        "price_factor": 0.8,
    },
]
