name: Keep Supabase Alive

on:
  schedule:
    - cron: '0 0 */3 * *' 
  workflow_dispatch:

jobs:
  ping-app:
    runs-on: ubuntu-latest
    steps:
      - name: Ping deployed API
        run: curl -s -f https://railway-ticketing-api.vercel.app/get-all-bookings -o /dev/null
